name: ðŸš€ Publish Codegen

on:
  push:
    branches: next
    paths: packages/create-vite-webext/**
  pull_request_target:
    branches: master
    types: closed
    paths: packages/create-vite-webext/**

jobs:
  publish:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [20.x]
        pnpm: [latest]
    runs-on: ${{ matrix.os }}
    permissions:
      id-token: write

    steps:
      - name: â¬‡ï¸ Checkout
        uses: actions/checkout@v3

      - name: ðŸŸ¢ Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: ðŸŸ¡ Setup pnpm
        id: setup-pnpm
        uses: pnpm/action-setup@v2.1.0
        with:
          version: ${{ matrix.pnpm }}
          run_install: false

      - name: ðŸ§­ Get pnpm store directory
        id: pnpm-config
        run: |
          echo "store_path=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: ðŸ’¾ Cache pnpm modules
        uses: actions/cache@v3
        id: pnpm-cache
        with:
          path: ${{ steps.pnpm-config.outputs.store_path }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: ðŸ§© Install dependencies
        run: pnpm install

      - name: ðŸ“¦ Build package
        run: npm run build

      - name: ðŸš€ Publish  create-vite-webext
        working-directory: ./packages/create-vite-webext
        run: |
          npm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
